# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
