# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-23 23:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 1, 23, 23, 0, 9, 108994, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
