# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-19 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180119_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_height',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_width',
        ),
    ]
